apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-text-diagram-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: dark_class_selector
          label: 暗黑模式的选择器
          value: "html[class~=dark]"
          help: 用于匹配暗黑模式的CSS选择器
        - $formkit: checkbox
          name: enable_client_mermaid_render
          id: enable_client_mermaid_render
          key: enable_client_mermaid_render
          label: 启用客户 Mermaid 端渲染
          help: 使用第三方编辑器时，需要启用此项以确保 Mermaid 正确渲染
          value: false
        - $formkit: text
          if: $get(enable_client_mermaid_render).value === true
          name: mermaid_selector
          label: mermaid-CSS选择器
          value: "text-diagram[data-type=mermaid]"
          help: 用于匹配mermaid的CSS选择器